/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Courier = { 'ekart' : null } |
  { 'delhivery' : null };
export interface OrderField {
  'customerName' : string,
  'status' : OrderStatus,
  'courier' : Courier,
  'estimatedDelivery' : bigint,
  'trackingId' : string,
  'orderId' : bigint,
  'totalAmount' : bigint,
  'address' : string,
  'placedAt' : bigint,
  'phone' : string,
  'items' : Array<OrderItem>,
  'pincode' : string,
}
export interface OrderItem { 'productId' : string, 'quantity' : bigint }
export type OrderStatus = { 'outForDelivery' : null } |
  { 'dispatched' : null } |
  { 'orderPlaced' : null } |
  { 'inTransit' : null } |
  { 'delivered' : null };
export interface _SERVICE {
  'getOrderByTracking' : ActorMethod<[string], [] | [OrderField]>,
  'getOrders' : ActorMethod<[], Array<OrderField>>,
  'placeOrder' : ActorMethod<
    [string, string, string, string, Array<[string, bigint]>, bigint],
    string
  >,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];