/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const OrderStatus = IDL.Variant({
  'outForDelivery' : IDL.Null,
  'dispatched' : IDL.Null,
  'orderPlaced' : IDL.Null,
  'inTransit' : IDL.Null,
  'delivered' : IDL.Null,
});
export const Courier = IDL.Variant({
  'ekart' : IDL.Null,
  'delhivery' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'productId' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const OrderField = IDL.Record({
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'courier' : Courier,
  'estimatedDelivery' : IDL.Int,
  'trackingId' : IDL.Text,
  'orderId' : IDL.Nat,
  'totalAmount' : IDL.Nat,
  'address' : IDL.Text,
  'placedAt' : IDL.Int,
  'phone' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
  'pincode' : IDL.Text,
});

export const idlService = IDL.Service({
  'getOrderByTracking' : IDL.Func([IDL.Text], [IDL.Opt(OrderField)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(OrderField)], ['query']),
  'placeOrder' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
        IDL.Nat,
      ],
      [IDL.Text],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const OrderStatus = IDL.Variant({
    'outForDelivery' : IDL.Null,
    'dispatched' : IDL.Null,
    'orderPlaced' : IDL.Null,
    'inTransit' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const Courier = IDL.Variant({ 'ekart' : IDL.Null, 'delhivery' : IDL.Null });
  const OrderItem = IDL.Record({
    'productId' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const OrderField = IDL.Record({
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'courier' : Courier,
    'estimatedDelivery' : IDL.Int,
    'trackingId' : IDL.Text,
    'orderId' : IDL.Nat,
    'totalAmount' : IDL.Nat,
    'address' : IDL.Text,
    'placedAt' : IDL.Int,
    'phone' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
    'pincode' : IDL.Text,
  });
  
  return IDL.Service({
    'getOrderByTracking' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(OrderField)],
        ['query'],
      ),
    'getOrders' : IDL.Func([], [IDL.Vec(OrderField)], ['query']),
    'placeOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
          IDL.Nat,
        ],
        [IDL.Text],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };