/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface OrderItem {
    productId: string;
    quantity: bigint;
}
export interface OrderField {
    customerName: string;
    status: OrderStatus;
    courier: Courier;
    estimatedDelivery: bigint;
    trackingId: string;
    orderId: bigint;
    totalAmount: bigint;
    address: string;
    placedAt: bigint;
    phone: string;
    items: Array<OrderItem>;
    pincode: string;
}
export enum Courier {
    ekart = "ekart",
    delhivery = "delhivery"
}
export enum OrderStatus {
    outForDelivery = "outForDelivery",
    dispatched = "dispatched",
    orderPlaced = "orderPlaced",
    inTransit = "inTransit",
    delivered = "delivered"
}
export interface backendInterface {
    getOrderByTracking(trackingId: string): Promise<OrderField | null>;
    getOrders(): Promise<Array<OrderField>>;
    placeOrder(customerName: string, phone: string, address: string, pincode: string, items: Array<[string, bigint]>, totalAmount: bigint): Promise<string>;
    updateOrderStatus(trackingId: string, status: OrderStatus): Promise<void>;
}
import type { Courier as _Courier, OrderField as _OrderField, OrderItem as _OrderItem, OrderStatus as _OrderStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getOrderByTracking(arg0: string): Promise<OrderField | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderByTracking(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderByTracking(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrders(): Promise<Array<OrderField>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrders();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrders();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async placeOrder(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Array<[string, bigint]>, arg5: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateOrderStatus(arg0: string, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Courier_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Courier): Courier {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_OrderField_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderField): OrderField {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OrderField]): OrderField | null {
    return value.length === 0 ? null : from_candid_OrderField_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    status: _OrderStatus;
    courier: _Courier;
    estimatedDelivery: bigint;
    trackingId: string;
    orderId: bigint;
    totalAmount: bigint;
    address: string;
    placedAt: bigint;
    phone: string;
    items: Array<_OrderItem>;
    pincode: string;
}): {
    customerName: string;
    status: OrderStatus;
    courier: Courier;
    estimatedDelivery: bigint;
    trackingId: string;
    orderId: bigint;
    totalAmount: bigint;
    address: string;
    placedAt: bigint;
    phone: string;
    items: Array<OrderItem>;
    pincode: string;
} {
    return {
        customerName: value.customerName,
        status: from_candid_OrderStatus_n4(_uploadFile, _downloadFile, value.status),
        courier: from_candid_Courier_n6(_uploadFile, _downloadFile, value.courier),
        estimatedDelivery: value.estimatedDelivery,
        trackingId: value.trackingId,
        orderId: value.orderId,
        totalAmount: value.totalAmount,
        address: value.address,
        placedAt: value.placedAt,
        phone: value.phone,
        items: value.items,
        pincode: value.pincode
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    outForDelivery: null;
} | {
    dispatched: null;
} | {
    orderPlaced: null;
} | {
    inTransit: null;
} | {
    delivered: null;
}): OrderStatus {
    return "outForDelivery" in value ? OrderStatus.outForDelivery : "dispatched" in value ? OrderStatus.dispatched : "orderPlaced" in value ? OrderStatus.orderPlaced : "inTransit" in value ? OrderStatus.inTransit : "delivered" in value ? OrderStatus.delivered : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ekart: null;
} | {
    delhivery: null;
}): Courier {
    return "ekart" in value ? Courier.ekart : "delhivery" in value ? Courier.delhivery : value;
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderField>): Array<OrderField> {
    return value.map((x)=>from_candid_OrderField_n2(_uploadFile, _downloadFile, x));
}
function to_candid_OrderStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    outForDelivery: null;
} | {
    dispatched: null;
} | {
    orderPlaced: null;
} | {
    inTransit: null;
} | {
    delivered: null;
} {
    return value == OrderStatus.outForDelivery ? {
        outForDelivery: null
    } : value == OrderStatus.dispatched ? {
        dispatched: null
    } : value == OrderStatus.orderPlaced ? {
        orderPlaced: null
    } : value == OrderStatus.inTransit ? {
        inTransit: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
